# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-07 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TruckModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TruckParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(max_length=200)),
                ('descrption', models.CharField(max_length=300)),
                ('service_price', models.PositiveIntegerField(max_length=7)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FastMotorsApp.TruckModels')),
            ],
        ),
    ]
