# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-07 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FastMotorsApp', '0002_auto_20200307_0757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truckparts',
            old_name='descrption',
            new_name='description',
        ),
    ]
