# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-07 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FastMotorsApp', '0003_auto_20200307_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_phone', models.IntegerField()),
                ('company_name', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_email', models.EmailField(max_length=254)),
                ('truck_registration', models.CharField(max_length=100)),
                ('truck_chassis', models.IntegerField()),
                ('engine_number', models.CharField(max_length=50)),
                ('car_mileage', models.IntegerField()),
                ('truck_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FastMotorsApp.TruckModels')),
            ],
        ),
    ]
