# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-07 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FastMotorsApp', '0004_securityentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_parts', models.BooleanField(default=True)),
                ('service_price', models.BooleanField(default=True)),
                ('truck_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FastMotorsApp.TruckModels')),
                ('truck_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FastMotorsApp.SecurityEntry')),
            ],
        ),
    ]
